export const fontFamily = {
	// Sambung/latin
	anastasiaScript: "'Anastasia Script', cursive",
	aniyah: "'Aniyah', cursive",
	beautiful: "'Beautiful', cursive",
	brightwall: "'Brightwall', cursive",
	farmhouse: "'Farmhouse', cursive",
	gistesy: "'Gistesy', cursive",
	holiday: "'Holiday', cursive",
	introScript: "'Intro Script', cursive",
	pacifico: "'Pacifico', cursive",
	pinyonScript: "'Pinyon Script', cursive",
	playlistScript: "'Playlist Script', cursive",
	retroSignature: "'Retro Signature', cursive",
	sallim: "'Sallim', cursive",
	sunsetHill: "'Sunset Hill', cursive",

	// Cartoon
	baksoSapi: "'Bakso Sapi', cursive",
	blueberry: "'Blueberry', cursive",
	cweyons: "'Cweyons', cursive",
	gamjaFlower: "'Gamja Flower', cursive",
	happyFont: "'Happy Font', cursive",
	heyTiny: "'Hey Tiny', cursive",
	jua: "'Jua', cursive",
	lazydog: "'Lazydog', cursive",
	lionCub: "'Lion Cub', cursive",
	luluFont: "'Lulu Font', cursive",
	marykate: "'Marykate', cursive",
	sundayMorning: "'Sunday Morning', cursive",
	winkle: "'Winkle', cursive",

	// Elegant
	brightRetro: "'Bright Retro', sans-serif",
	margin: "'Margin', sans-serif",
	quiche: "'Quiche', sans-serif",
	recoleta: "'Recoleta', serif",
	sergioTrendy: "'Sergio Trendy', sans-serif",
	tanPearl: "'Tan Pearl', serif",

	// Serif
	argent: "'Argent', serif",
	arial: "'Arial', sans-serif",
	futura: "'Futura', sans-serif",
	garamond: "'Garamond', serif",
	helvetica: "'Helvetica', sans-serif",
	josefinSans: "'Josefin Sans', sans-serif",
	lancelot: "'Lancelot', serif",
	leagueSpartan: "'League Spartan', sans-serif",
	libreBaskerville: "'Libre Baskerville', serif",
	lora: "'Lora', serif",
	montserrat: "'Montserrat', sans-serif",
	poppins: "'Poppins', sans-serif",
	sourceSerifPro: "'Source Serif Pro', serif",
	timesNewRoman: "'Times New Roman', serif",
	typoFormal: "'Typo Formal', serif",
	workSans: "'Work Sans', sans-serif",

	// Unknown
	"29ltMakina": "'29LT Makina', sans-serif",
	alice: "'Alice', serif",
	amsterdamFour: "'Amsterdam Four', sans-serif",
	archivoBlack: "'Archivo Black', sans-serif",
	autumnInNovember: "'Autumn in November', cursive",
	bethEllen: "'Beth Ellen', cursive",
	brownSugar: "'Brown Sugar', cursive",
	bubbly: "'Bubbly', cursive",
	bugaki: "'Bugaki', sans-serif",
	canvaSans: "'Canva Sans', sans-serif",
	cocogoose: "'Cocogoose', sans-serif",
	crimsonPro: "'Crimson Pro', serif",
	flatlion: "'Flatlion', sans-serif",
	glacialIndifference: "'Glacial Indifference', sans-serif",
	halimun: "'Halimun', sans-serif",
	janethville: "'Janethville', cursive",
	laLuxesScript: "'La Luxes Script', cursive",
	lekton: "'Lekton', serif",
	moreSugar: "'More Sugar', cursive",
	mungil: "'Mungil', sans-serif",
	quincyCF: "'Quincy CF', sans-serif",
	rocaTwo: "'Roca Two', sans-serif",
	spaceMono: "'Space Mono', monospace",
	theSeasons: "'The Seasons', cursive",
	ttNorms: "'TT Norms', sans-serif",
};

export type FontType = typeof fontFamily;

export const fontArray = Object.entries(fontFamily).map(
	([fontname, fontfamily]) => ({
		fontname,
		fontfamily,
	}),
);
