import type { TemplateData } from "@/shared/types/template";

export const template5: TemplateData = {
	id: "graduation-collage",
	name: "Graduation Collage",
	width: 600,
	height: 800,
	backgroundColor: "#ffffff",
	images: [
		{
			id: "image-1",
			type: "image",
			src: "/placeholder.png",
			position: { x: 50, y: 100 },
			width: 240,
			height: 240,
		},
		{
			id: "image-2",
			type: "image",
			src: "/placeholder.png",
			position: { x: 300, y: 100 },
			width: 240,
			height: 240,
		},
		{
			id: "image-3",
			type: "image",
			src: "/placeholder.png",
			position: { x: 50, y: 350 },
			width: 240,
			height: 240,
		},
		{
			id: "image-4",
			type: "image",
			src: "/placeholder.png",
			position: { x: 300, y: 350 },
			width: 240,
			height: 240,
		},
	],
	texts: [
		{
			id: "text-1",
			type: "text",
			content: "Happy Graduation",
			position: { x: 0, y: 600 },
			style: {
				fontFamily: "'Segoe UI', sans-serif",
				fontSize: "38px",
				fontWeight: "normal",
				color: "#000000",
				textAlign: "center",
				lineHeight: "1.2",
				centerX: true,
				maxWidth: 600,
			},
		},
		{
			id: "text-2",
			type: "text",
			content: "Name ♥",
			position: { x: 0, y: 660 },
			style: {
				fontFamily: "'Segoe UI', sans-serif",
				fontSize: "14px",
				fontWeight: "bold",
				color: "#000000",
				textAlign: "center",
				lineHeight: "1.2",
				centerX: true,
				maxWidth: 600,
				backgroundColor: "#d9d9d9",
				borderRadius: 25,
				paddingX: 20,
				paddingY: 10,
			},
		},
		{
			id: "text-3",
			type: "text",
			content:
				"Congratulations you have completed your first step well and good luck for the next step of your journey.",
			position: { x: 0, y: 700 },
			style: {
				fontFamily: "'Segoe UI', sans-serif",
				fontSize: "12px",
				fontWeight: "normal",
				color: "#666666",
				textAlign: "center",
				lineHeight: "1.4",
				centerX: true,
				maxWidth: 300,
			},
		},
	],
};
